project:
  name: SegFormer_ENH
  experiment_name: SegFormer_ENH
data:
  input_mode: enh
  input_dir: ./data/Input/ENH/
  target_dir: ./data/Target/
  fold_csv: ./data/Input/all_patches_with_folds.csv
  norm_param_dir: ./data/Norm_parameters/ENH/
  norm_files:
    min: min.npy
    max: max.npy
    mean: mean.npy
    std: std.npy
  normalization: minmax
train:
  n_folds: 5
  epochs: 500
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.01
  max_grad_norm: 2.0
  patience: 200
  num_workers: 4
  seed: 1004
  amp: true
model:
  arch: segformer
  in_channels: 1
  num_labels: 1
logging:
  use_wandb: true
  save_root: ./outputs
